version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nest_postgres_db
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nest_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
